version: "3"

x-mysql-environment: &mysql-environment
    MYSQL_USER: ${MYSQL_USER}
    MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    MYSQL_DATABASE: ${MYSQL_DATABASE}
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        networks:
            docker-network:
                ipv4_address: 172.27.0.2
    mysql:
        image: mariadb:10.5-focal
        environment:
            <<: *mysql-environment
        volumes:
            - db-data:/var/lib/mysql
        networks:
            docker-network:
                ipv4_address: 172.27.0.4
        healthcheck:
            test: [ "CMD", "mysqladmin", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "ping" ]
            interval: 15s
            timeout: 3s
            retries: 3
            start_period: 15s

    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - php-data:/var/www
        environment:
            <<: *mysql-environment
        networks:
            docker-network:
                ipv4_address: 172.27.0.3
        depends_on:
            mysql:
                condition: service_healthy

volumes:
    php-data:
    db-data:

networks:
    docker-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.27.0.0/24
